normal:
  lambda_normal: 0.1
  lambda_distortion: 1.0
  apply_normal_after_step: 10000
  apply_distortion_after_step: 5000

  valid_threshold: 0.1
  depth_valid_threshold: 1e-3
  depth_disc_multiplier: 3.0
  depth_disc_slope: 0.2
  huber_delta: 0.1
